# Generated by Django 5.0.6 on 2024-09-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/pdfs/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
