# Generated by Django 5.0.6 on 2024-09-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0002_document_pdf_file_alter_document_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='content',
            new_name='description',
        ),
    ]
