# Generated by Django 5.0.6 on 2024-09-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0003_rename_content_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('challenge', 'Challenge'), ('project', 'Project'), ('module', 'Module')], default='Choose an option', max_length=10),
        ),
    ]
