# Generated by Django 5.0.6 on 2024-09-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0004_document_document_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='pdf_file',
            new_name='upload_file',
        ),
    ]
