# Generated by Django 5.0.6 on 2024-09-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0005_rename_pdf_file_document_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('country', models.CharField(choices=[('us', 'United States'), ('moldova', 'Moldova')], max_length=20)),
                ('subject', models.CharField(choices=[('bio', 'Biology'), ('chem', 'Chemistry'), ('phys', 'Physics'), ('ps', 'Physocal Science (US)'), ('ls', 'Life Science (US)'), ('ess', 'Earth and Space Science (US)')], max_length=50)),
                ('grade_level', models.CharField(choices=[('4', '4th Grade'), ('5', '5th Grade'), ('6', '6th Grade'), ('7', '7th Grade'), ('8', '8th Grade'), ('9', '9th Grade')], max_length=10)),
            ],
        ),
    ]
