# Generated by Django 5.0.6 on 2024-09-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0006_lessonstandard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstandard',
            name='subject',
            field=models.CharField(choices=[('bio', 'Biology'), ('chem', 'Chemistry'), ('phys', 'Physics'), ('ps', 'Physical Science (US)'), ('ls', 'Life Science (US)'), ('ess', 'Earth and Space Science (US)')], max_length=50),
        ),
    ]
