# Generated by Django 5.0.6 on 2024-09-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0008_country_document_standards_grade_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(choices=[('us', 'United States'), ('moldova', 'Moldova')], max_length=100),
        ),
    ]
