# Generated by Django 5.0.6 on 2024-10-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0009_alter_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='country',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
