# Generated by Django 5.0.6 on 2024-10-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0010_remove_grade_country_delete_subject_delete_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('grade_level', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('entered_by', models.CharField(max_length=50)),
                ('materials', models.TextField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('question_idea', models.TextField(blank=True, null=True)),
                ('hypothesis', models.TextField(blank=True, null=True)),
                ('experiemnt_test', models.TextField(blank=True, null=True)),
                ('results_analysis', models.TextField(blank=True, null=True)),
                ('communication', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
