# Generated by Django 5.0.6 on 2024-10-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0011_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
